### ISSUE TITLE
Traceback: 'serial' is invalid. Failed to add device/vsys to device group

### ISSUE THREAD

**Issue by btorresgil** [PaloAltoNetworks/cisco-aci-devicepackage#1]
Get the following traceback when adding a multi-context vsys to a device-group using Panorama:

```
YYYY-MM-DD 00:00:00.000000 ERROR Thread-1 1416614 [10.10.10.10, 141251] serviceAudit: Traceback (most recent call last):
  File "/install/lib/faulthandler.py", line 53, in handler
    return_value = method(*argv, **kwargs)
  File "/install/lib/apichandler.py", line 173, in service_audit
    model.apply_to_devices()
  File "/install/lib/configmodel/configmodel.py", line 207, in apply_to_devices
    self.apply_security()
  File "/install/lib/configmodel/configmodel.py", line 420, in apply_security
    relation.apply_to_devices()
  File "/install/lib/configmodel/confignodetypes.py", line 183, in apply_to_devices
    self.folder.apply_to_devices(self.state if self.state > inherited_state and self.state != State.DELETED else inherited_state)
  File "/install/lib/configmodel/confignodetypes.py", line 108, in apply_to_devices
    self._finalize(inherited_state=inherited_state)
  File "/install/lib/configmodel/confignodesubs.py", line 802, in _finalize
    fw.create()
  File "/install/lib/pandevice/pandevice/firewall.py", line 267, in create
    panorama.xapi.set(self.xpath_short(), element)
  File "/install/lib/pandevice/pandevice/base.py", line 1531, in method
    raise the_exception
PanDeviceXapiError:  000123456789 '000123456789' is invalid. Failed to add device/vsys to device group
```

**Comment by btorresgil** [comment]
Fixed in device package version 1.1.1
