### ISSUE TITLE
Traceback: TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by btorresgil** [PaloAltoNetworks/cisco-aci-devicepackage#2]
Traceback when removing VSYS:

```
YYYY-MM-DD 00:00:00.000000 ERROR Thread-12 1418417 [10.10.10.10, 151562] serviceAudit: HANDLING UNEXPECTED EXCEPTION
YYYY-MM-DD 00:00:00.000000 ERROR Thread-12 1418418 [10.10.10.10, 151562] serviceAudit: Traceback (most recent call last):
  File "/install/lib/faulthandler.py", line 53, in handler
    return_value = method(*argv, **kwargs)
  File "/install/lib/apichandler.py", line 173, in service_audit
    model.apply_to_devices()
  File "/install/lib/configmodel/configmodel.py", line 159, in apply_to_devices
    self.apply_service_scope()
  File "/install/lib/configmodel/configmodel.py", line 360, in apply_service_scope
    self._delete_vsys(vsys)
  File "/install/lib/configmodel/configmodel.py", line 461, in _delete_vsys
    self.delete_vsys_interfaces(vsys=vsys)
  File "/install/lib/configmodel/configmodel.py", line 574, in delete_vsys_interfaces
    interface.full_delete(refresh=refresh, delete_referencing_objects=True)
  File "/install/lib/pandevice/pandevice/network.py", line 341, in full_delete
    elif str(self) in obj.interface:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by btorresgil** [comment]
Fixed in device package version 1.1.1
