### ISSUE TITLE
Traceback: IndexError: tuple index out of range

### ISSUE THREAD

**Issue by btorresgil** [PaloAltoNetworks/cisco-aci-devicepackage#3]
Traceback can appear in logs when using Layer2 interfaces:

```
YYYY-MM-DD 00:00:00.000000 ERROR Thread-19 107935 [10.10.10.10, 3674] serviceAudit: HANDLING UNEXPECTED EXCEPTION
YYYY-MM-DD 00:00:00.000000 ERROR Thread-19 107936 [10.10.10.10, 3674] serviceAudit: Traceback (most recent call last):
  File "/install/lib/faulthandler.py", line 53, in handler
    return_value = method(*argv, **kwargs)
  File "/install/lib/apichandler.py", line 173, in service_audit
    model.apply_to_devices()
  File "/install/lib/configmodel/configmodel.py", line 159, in apply_to_devices
    self.apply_service_scope()
  File "/install/lib/configmodel/configmodel.py", line 374, in apply_service_scope
    encapass.apply_to_devices()
  File "/install/lib/configmodel/confignodetypes.py", line 231, in apply_to_devices
    encaprel.apply_to_devices()
  File "/install/lib/configmodel/confignodetypes.py", line 305, in apply_to_devices
    connector.apply_to_devices(self.state if self.state != State.DELETED else None)
  File "/install/lib/configmodel/confignodetypes.py", line 86, in apply_to_devices
    relation.apply_to_devices(inherited_state)
  File "/install/lib/configmodel/confignodetypes.py", line 183, in apply_to_devices
    self.folder.apply_to_devices(self.state if self.state > inherited_state and self.state != State.DELETED else inherited_state)
  File "/install/lib/configmodel/confignodetypes.py", line 108, in apply_to_devices
    self._finalize(inherited_state=inherited_state)
  File "/install/lib/configmodel/confignodesubs.py", line 465, in _finalize
    layer_folder.apply_to_devices(inherited_state)
  File "/install/lib/configmodel/confignodetypes.py", line 108, in apply_to_devices
    self._finalize(inherited_state=inherited_state)
  File "/install/lib/configmodel/confignodesubs.py", line 602, in _finalize
    interface = self._handle_abstract_subinterface(interface, mode)
  File "/install/lib/configmodel/confignodesubs.py", line 620, in _handle_abstract_subinterface
    subinterface = interface.get_layered_subinterface(mode, add=True)
  File "/install/lib/pandevice/pandevice/network.py", line 559, in get_layered_subinterface
    layered_subinterface = self.parent.add(subintclass(self.name, tag=self.tag))
  File "/install/lib/pandevice/pandevice/base.py", line 1185, in __init__
    super(VsysImportMixin, self).__init__(*args, **kwargs)
  File "/install/lib/pandevice/pandevice/network.py", line 453, in __init__
    super(Subinterface, self).__init__(*args, **kwargs)
  File "/install/lib/pandevice/pandevice/network.py", line 208, in __init__
    super(Interface, self).__init__(*args, **kwargs)
  File "/install/lib/pandevice/pandevice/base.py", line 82, in __init__
    variables = type(self).variables()
  File "/install/lib/pandevice/pandevice/network.py", line 617, in variables
    modevar = filter(lambda var: var.variable == "mode", variables)[0]
IndexError: tuple index out of range
```

**Comment by btorresgil** [comment]
Fixed in device package version 1.1.1
